apiVersion: v1
entries:
  bluecompute-auth:
  - apiVersion: v1
    created: 2017-05-05T13:24:49.148568906-05:00
    description: BlueCompute Auth Microservice
    digest: 4cd302dddc03e8131f0764f27cb01fd885f75cc9e785fc442fd72445a860cb73
    name: bluecompute-auth
    urls:
    - bluecompute-auth-0.1.0.tgz
    version: 0.1.0
  bluecompute-catalog:
  - apiVersion: v1
    created: 2017-05-05T13:24:49.148822101-05:00
    description: BlueCompute Catalog Microservice
    digest: c07d66294236172ab84ee95e50c9cc6a506b23bd529709bc45e76700af76c1a2
    name: bluecompute-catalog
    urls:
    - bluecompute-catalog-0.1.1.tgz
    version: 0.1.1
  bluecompute-inventory:
  - apiVersion: v1
    created: 2017-05-05T13:24:49.14902028-05:00
    description: BlueCompute Inventory Microservice
    digest: a4ee31803635d7ea487b180a2e208aedb94b779f395780e39df23bab44f0b0b3
    name: bluecompute-inventory
    urls:
    - bluecompute-inventory-0.1.1.tgz
    version: 0.1.1
  bluecompute-web:
  - apiVersion: v1
    created: 2017-05-05T13:24:49.149202919-05:00
    description: BlueCompute Web BFF app
    digest: f6bb749af7692ef34629a17b201d5ece3f28acd9cf29aaf58edf5c225e740c4b
    name: bluecompute-web
    urls:
    - bluecompute-web-0.1.0.tgz
    version: 0.1.0
generated: 2017-05-05T13:24:49.147581474-05:00
