---
stages:
- name: Build
  inputs:
  - url: https://github.com/ssibm/refarch-cloudnative-bff-inventory.git
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: npm
    type: builder
    working_dir: inventory
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: npm
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: cent@us.ibm.com
      space: cloudnative-qa
      application: inventory-bff-qa
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -n ${CF_APP}
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
