---
stages:
- name: BUILD
  inputs:
  - service: ${REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  properties:
  - name: APIC_URL
    value: ${APIC_URL}
    type: text
  - name: APIC_USER
    value: ${APIC_USER}
    type: text
  - name: APIC_PASS
    value: ${APIC_PASS}
    type: secure
  - name: ORG
    value: ${ORG}
    type: text
  - name: SPACE
    value: ${SPACE}
    type: text
  - name: APP_NAME
    value: ${NAME}
    type: text
  - name: DOMAIN
    value: ${DOMAIN}
    type: text
  - name: JWT_SHARED_SECRET
    value: ${JWT_SHARED_SECRET}
    type: text
  jobs:
  - name: Publish Inventory BFF
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      #npm install
      echo $PWD
      ls -al .
      # set orgs
      CHARLST="[@|.|-|_]"
      ORGS=$(echo $ORG|sed "s/$CHARLST//g")-$SPACE
      # Configure APIC cli
      echo -e "Start installing apiconnect cli"
      npm install -g apiconnect
      echo -e "completed installing apic cli"
      echo "yes" | apic

      cd inventory
      echo -e "Set TARGET_HOST"
      TARGET_HOST=$APP_NAME.$DOMAIN
      sed -i -e "/^x\-ibm\-configuration\:$/,/^.*\:$ /{/properties\:$/,/$/{/TARGET\_HOST\:$/{N;s/\(value\:\)\(.*$\)/\1 \'https\:\/\/$TARGET_HOST\'/}}}" -e 's/\(\\ \\"k\\"\: \\"\)\(.*\)\(\\"\\\)/\1JSONWEBTOKENSHAREDSECRET\3/' -e "s/JSONWEBTOKENSHAREDSECRET/$JWT_SHARED_SECRET"/ inventory.yaml
      cat inventory.yaml

      echo -e "Publish the inventory api"
      apic login -u $APIC_USER -p $APIC_PASS -s ${APIC_URL}
      apic config:set catalog=apic-catalog://${APIC_URL}/orgs/${ORGS}/catalogs/bluecompute
      apic publish inventory-product_0.0.1.yaml
