---
stages:
- name: BUILD
  inputs:
  - service: ${REPO}
    type: git
    branch: master
  properties:
  - name: APP_DOMAIN
    value: ${DOMAIN}
    type: text
  - name: ZUUL_PROXY_URL
    value: ${ZUUL_PROXY_URL}
    type: text
  - name: CTXPATH
    value: ${CTXPATH}
    type: text
  - name: SOCIALREVIEW_MSNAME
    value: ${SOCIALREVIEW_MSNAME}
    type: text
  jobs:
  - name: Build Inventory BFF
    type: builder
    working_dir: inventory
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      /bin/bash set-zuul-proxy-url.sh -c $CTXPATH -m $INVENTORY_MSNAME -z $ZUUL_PROXY_URL
      npm install
- name: DEPLOY
  inputs:
  - type: job
    stage: Build
    job: Build Inventory BFF
  triggers:
  - type: stage
  jobs:
  - name: Deploy Inventory BFF
    type: deployer
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
      application: ${NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -n ${CF_APP} -d ${APP_DOMAIN}
