dependencies:
  - name: bluecompute-catalog
    version: 0.1.1
    repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-devops/charts
  - name: bluecompute-inventory
    version: 0.1.1
    repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-devops/charts