dependencies:
  - name: catalog
    version: 0.1.1
    repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-devops/charts
  - name: inventory
    version: 0.1.1
    repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-devops/charts